package stellar.io;

public enum States 
    {
        NAME_WORD, NAME_NUMBER, HEXID, UWP, BASE, REMARK, ZONE, PBG, ALEG,
        PRIMARY_CODE, PRIMARY_TYPE, SECONDARY_CODE, SECONDARY_TYPE, 
        TERTIARY_CODE, TERTIARY_TYPE, LRX, SATELLITE, UNUSED, FINISHED, ERROR;
    }

